---
name: Bump Version and Publish Docker

on:
  pull_request:
    types: [closed]
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  bump-version-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Bump Version
        id: bump
        run: |
          import re
          import os

          pr_title = os.environ['PR_TITLE']
          with open('VERSION', 'r') as f:
              version = f.read().strip()
          major, minor, patch = map(int, version.split('.'))

          if '[BUMP_MAJOR]' in pr_title:
              major += 1
              minor = 0
              patch = 0
          elif '[BUMP_MINOR]' in pr_title:
              minor += 1
              patch = 0
          else:
              patch += 1

          new_version = f"{major}.{minor}.{patch}"
          with open('VERSION', 'w') as f:
              f.write(new_version)

          print(f"::set-output name=version::{new_version}")
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add VERSION
          git commit -m "Bump version to ${{ steps.bump.outputs.version }}"
          git push

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.bump.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64

      - name: Delete old images
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: true

